### ISSUE TITLE
Creating a new cipher fails on Vaultwarden

### ISSUE THREAD

**Issue by ilyakooo0** [ilyakooo0/warden#18]
The problems seems to stem from `CollectionIds` being non-nullable.

https://github.com/dani-garcia/vaultwarden/blob/45122bed9e2e48418e74b73c9a50c7608d3b6ac1/src/api/core/ciphers.rs#L631

This is the resulting error:

```
Error: An error occurred while decoding a JSON value:
  At object key 'ciphers':
  Under 'Array':
  At array index 322:
  At object key 'secureNote':
  At object key 'type':
  No value was found.
    at error (backend.js:55921:12)
    at $$throw (backend.js:55956:27)
    at __do2 (backend.js:61228:24)
    at backend.js:50895:18
    at backend.js:50895:22
    at backend.js:55935:18
    at __do2 (backend.js:62446:50)
    at backend.js:50895:18
    at backend.js:50895:22
    at backend.js:50895:18
```

**Comment by ilyakooo0** [comment]
Update: the stacktrace error is from a response
